version: '3'

services:
  deployment:
    build: deployment
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    environment:
      HOME: /tmp
    command: jupyter lab -y --no-browser --ip=0.0.0.0 --port=8884 --notebook-dir=/opt/project/ --NotebookApp.token=${DEPLOYMENT_JUPYTER_TOKEN:?Run ./run.sh to generate Jupyter tokens}
    shm_size: '2gb'
    volumes:
      - './deployment/code/:/opt/project/'
      - './models:/opt/models/'
    ports:
      - "127.0.0.1:8884:8884"
  training:
    build: training
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    environment:
      HOME: /tmp
    command: jupyter lab -y --no-browser --ip=0.0.0.0 --port=8883 --notebook-dir=/opt/project/ --NotebookApp.token=${TRAINING_JUPYTER_TOKEN:?Run ./run.sh to generate Jupyter tokens}
    volumes:
      - './training/code/:/opt/project/'
    ports:
      - "127.0.0.1:8883:8883"
  data-generation:
    build: data_generation
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    environment:
      HOME: /tmp
    command: jupyter lab -y --no-browser --ip=0.0.0.0 --port=8882 --notebook-dir=/opt/project/ --NotebookApp.token=${DATA_GENERATION_JUPYTER_TOKEN:?Run ./run.sh to generate Jupyter tokens}
    volumes:
      - './data_generation/code/:/opt/project/'
    ports:
      - "127.0.0.1:8882:8882"
